### PR TITLE
Pretrained embeddings 

### PR DESCRIPTION
**Pull request by popcornell**
This PR supersedes https://github.com/DCASE-REPO/DESED_task/pull/35 
Adding AST and PANNs Audioset-based pretrained models. 
Right now supports e2e training. 
Also the script to extract the embedding to use them offline is included.

### CODE REVIEW

**Comment by popcornell** [comment]
@RonFrancesca @turpaultn ready for review. 
Right now the code supports both fine-tuning of the model and using pre-extracted embeddings

**Comment by popcornell** [comment]
Once the embeddings are in dropbox and we agree on how participants can download them. I ll add instructions in the readme

**Comment by turpaultn** [comment]
I have uploaded the embeddings to zenodo: 
- https://zenodo.org/record/6541454#.YnzHq2YzbDI (unalabeled ast)
- https://zenodo.org/record/6539466#.YnvtWmYzbAM (ast synth train, ast synth val,ast weak val)
- https://zenodo.org/record/6518380#.YnvWZGYzbAM (panns, ast weak train, ast devtest)

**Comment by popcornell** [comment]
I added the instructions on the README.md on how to run the baseline with pre-trained models. 
Plus the results for the best model.

**Comment by popcornell** [comment]
@RonFrancesca can you review ?

**Comment by RonFrancesca** [comment]
@popcornell overwall the code is great!
Thanks for the work!

In particular:
- I added some minor comments on the text of the README file with suggestions
- I would remove the two empty __init__.py files
- I would not delete the line 99 on the datasets.py file, otherwise the KeyAttribute error would be thrown.

**Comment by popcornell** [comment]
I can't see your comments on README

**Review by RonFrancesca — CHANGES_REQUESTED** [review]

**Comment by RonFrancesca** [comment]
> Nope I am sorry. Did you submit your review ?

Now you should be able to see them, I guess

**Comment by popcornell** [comment]
I should ve addressed your comments

**Comment by popcornell** [comment]
Can we merge this ?

**Review by RonFrancesca — APPROVED** [review]

**Pull request merged**
